### ISSUE TITLE
Current timestamp timezone definition

### ISSUE THREAD

**Issue by grctest** [ThomasFreedman/hertz-feed#1]
I remembered that when testing the script in Google Colab, python couldn't retrieve a default timezone from the local environment (despite my server's python environment doing so), so perhaps try the following:

Please try changing [line 64](https://github.com/ThomasFreedman/hertz-feed/blob/master/hertz-feed-standalone.py#L74)

```
hertz_current_timestamp = pendulum.now().timestamp() # Current timestamp for reference within the hertz script
```

To the following:

```
tz = pendulum.timezone('UTC') # Timezone needs defined
hertz_current_timestamp = pendulum.now(tz).timestamp() # Current timestamp for reference within the hertz script
```

This will explicitly specify UTC as the timezone required for the current timestamp generation.

**Comment by ThomasFreedman** [comment]
I will update it and we'll see if that's the issue or not.

**Comment by grctest** [comment]
This wasn't the problem in the end, no worries 👍
